# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 330968e969e5e8e9f634f1898b3b9dd4ec29b18c300e28ce4875c9a59b2eb28bc0e272dd4cdc76997ed82b91313fd87bc296aedd001586c30d07c686b4e0f299

test:
  secret_key_base: 81066b897f8eee39fd67f1b157357922dbcc0bd1072e28182803d9d6a51aa2756436ca5e014c06ab08c59c3577427af004f0f0bf06e617e649bcd47583bb551b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
